scripts:
  - name: Install dependencies
    script: |
      npm install --legacy-peer-deps
  - name: Set Gradle wrapper permissions
    script: |
      chmod +x android/gradlew
  - name: Verify native_modules.gradle exists
    script: |
      if [ ! -f node_modules/@react-native-community/cli-platform-android/native_modules.gradle ]; then
        echo "native_modules.gradle is missing, npm install might have failed."
        exit 1
      fi
  - name: Build Android release
    script: |
      cd android
      ./gradlew assembleRelease
